### PR TITLE
Fix: Add support for UserCredentials

### LINKED ISSUE #20: Service accounts only, no support for user accounts? "AttributeError: 'Credentials' object has no attribute 'service_account_email'"
### Background context

I'm trying to migrate services from a self-hosted Kafka cluster to a Google-hosted cluster.  We are trying to use this `managedkafka` proxy to manage the OAuth tokens.

An important requirement for us is that developers need to be able to publish & consume messages when running a service locally.  For example if I am adding a new feature to a service, I need to be able to test it locally, pointing to a Kafka cluster in our QA environment.

### The issue

I have a testbed which lets me experiment with this migration, publishing 10 messages and then consuming them back.  It works great with our self-hosted cluster, but when I configure it to use this proxy (with [the settings in the README](https://github.com/googleapis/managedkafka?tab=readme-ov-file#local-auth-server)) it fails to authenticate.

My environment is:

* OS: MacOS Sonoma 14.5
* JDK: Amazon Corretto 8.0.412
* Apache `kafka-clients` version 3.4.1

I see errors in the auth proxy logs and exceptions in the JVM testbed.  In my Java service I see this:

```
16:41:32.103 [main] WARN  o.a.k.c.s.o.internals.secured.Retry - Error during retry attempt 1
java.util.concurrent.ExecutionException: java.io.IOException: The token endpoint response was unexpectedly empty despite response code 200 from http://localhost:14293 and error message {}
	at org.apache.kafka.common.security.oauthbearer.internals.secured.HttpAccessTokenRetriever.lambda$retrieve$0(HttpAccessTokenRetriever.java:171)
	at org.apache.kafka.common.security.oauthbearer.internals.secured.Retry.execute(Retry.java:70)
	at org.apache.kafka.common.security.oauthbearer.internals.secured.HttpAccessTokenRetriever.retrieve(HttpAccessTokenRetriever.java:160)
	at org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler.handleTokenCallback(OAuthBearerLoginCallbackHandler.java:244)
	at org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler.handle(OAuthBearerLoginCallbackHandler.java:233)
	at org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule.identifyToken(OAuthBearerLoginModule.java:316)
	at org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule.login(OAuthBearerLoginModule.java:301)
(dozens of lines edited out by me)
Caused by: java.io.IOException: The token endpoint response was unexpectedly empty despite response code 200 from http://localhost:14293 and error message {}
	at org.apache.kafka.common.security.oauthbearer.internals.secured.HttpAccessTokenRetriever.handleOutput(HttpAccessTokenRetriever.java:275)
	at org.apache.kafka.common.security.oauthbearer.internals.secured.HttpAccessTokenRetriever.post(HttpAccessTokenRetriever.java:194)
	at org.apache.kafka.common.security.oauthbearer.internals.secured.HttpAccessTokenRetriever.lambda$retrieve$0(HttpAccessTokenRetriever.java:169)
	... 38 common frames omitted
```

In the auth proxy console I see this:

```
Exception occurred during processing of request from ('127.0.0.1', 53661)
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 692, in process_request_thread
    self.finish_request(request, client_address)
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/server.py", line 424, in handle_one_request
    method()
  File "/Users/jimmccabe/bin/gcloud/managedkafka/kafka-auth-local-server/kafka_gcp_credentials_server.py", line 98, in do_POST
    self._handle()
  File "/Users/jimmccabe/bin/gcloud/managedkafka/kafka-auth-local-server/kafka_gcp_credentials_server.py", line 89, in _handle
    message = build_message().encode('utf-8')
              ^^^^^^^^^^^^^^^
  File "/Users/jimmccabe/bin/gcloud/managedkafka/kafka-auth-local-server/kafka_gcp_credentials_server.py", line 75, in build_message
    access_token=get_kafka_access_token(creds),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jimmccabe/bin/gcloud/managedkafka/kafka-auth-local-server/kafka_gcp_credentials_server.py", line 64, in get_kafka_access_token
    [b64_encode(_HEADER), b64_encode(get_jwt(creds)), b64_encode(creds.token)]
                                     ^^^^^^^^^^^^^^
  File "/Users/jimmccabe/bin/gcloud/managedkafka/kafka-auth-local-server/kafka_gcp_credentials_server.py", line 49, in get_jwt
    sub=creds.service_account_email,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Credentials' object has no attribute 'service_account_email'
----------------------------------------
127.0.0.1 - - [05/Sep/2024 16:41:32] "POST / HTTP/1.1" 200 -
```

I am authenticated with `gcloud` locally, but I have user credentials, not a service account.  Individual `gcloud` auth is sufficient with other Google libs that we use, for example Cloud Storage and Secrets.

* Does this proxy only work when running inside of a Kubernetes cluster?
* Does it only work with service accounts, and not with user credentials?

The README says this:

> In either case, your client leverages Google Auth libraries for authentication using default environment credentials. On GCP environments like GKE or GCE, this typically implies using the environment service accounts. You can override this behavior and specify different credentials using the GOOGLE_APPLICATION_CREDENTIALS environment variable, as detailed in [this article](https://github.com/googleapis/google-auth-library-java?tab=readme-ov-file#getting-application-default-credentials).

I don't have a `GOOGLE_APPLICATION_CREDENTIALS` environment variable, but I am definitely authenticated with `gcloud auth`.  For example, `gcloud auth list` shows my credentialed account, `gcloud auth application-default print-access-token` successfully prints out a token, etc.

### PR DESCRIPTION
**Pull request by acocuzzo**
🛠️ Fixes #20

### CODE REVIEW

File: kafka-java-auth/src/main/java/com/google/cloud/hosted/kafka/auth/GcpLoginCallbackHandler.java [hunk 1]
```diff
@@ -104,8 +112,8 @@ public void handle(Callback[] callbacks) throws UnsupportedCallbackException, IO
     }
 
     for (Callback callback : callbacks) {
-      if (callback instanceof OAuthBearerTokenCallback) {
-        handleTokenCallback((OAuthBearerTokenCallback) callback);
+      if (callback instanceof OAuthBearerTokenCallback oAuthBearerTokenCallback) {
```
Comment (benjamin-maynard) [inline kafka-java-auth/src/main/java/com/google/cloud/hosted/kafka/auth/GcpLoginCallbackHandler.java:115]:
```
The Java feature 'Type Patterns' is only available with source level 16 and above
```

Had to update `kafka-java-auth/pom.xml`:
 
```
<maven.compiler.release>16</maven.compiler.release>
```

File: kafka-java-auth/src/main/java/com/google/cloud/hosted/kafka/auth/GcpLoginCallbackHandler.java [hunk 2]
```diff
@@ -18,10 +18,15 @@
 
 import static java.nio.charset.StandardCharsets.UTF_8;
 
+import com.google.api.client.googleapis.auth.oauth2.GoogleIdToken;
```
Comment (benjamin-maynard) [inline kafka-java-auth/src/main/java/com/google/cloud/hosted/kafka/auth/GcpLoginCallbackHandler.java:21]: Think we need to add `google-api-client` to `kafka-java-auth/pom.xml` 

```
    <dependency>
      <groupId>com.google.api-client</groupId>
      <artifactId>google-api-client</artifactId>
      <version>1.32.1</version>
    </dependency>
```

**Review by benjamin-maynard — COMMENTED** [review]
Tested locally with suggested changes and works as intended:

```bash
benmaynard$ cat ~/.config/gcloud/application_default_credentials.json 
{
  ... redacted...
  "type": "authorized_user",
  "universe_domain": "googleapis.com"
}

benmaynard$ cat client.properties 
security.protocol=SASL_SSL
sasl.mechanism=OAUTHBEARER
sasl.login.callback.handler.class=com.google.cloud.hosted.kafka.auth.GcpLoginCallbackHandler
sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;

benmaynard$ kafka-topics.sh --list --bootstrap-server $BOOTSTRAP --command-config client.properties
__remote_log_metadata
flink-artifacts
gmk-test
```

**Comment by stankiewicz** [comment]
thanks for working on this @acocuzzo ! this looks great and solves my problem with testing with adc.

File: kafka-java-auth/src/main/java/com/google/cloud/hosted/kafka/auth/GcpLoginCallbackHandler.java (hunk 2 above)
Comment (acocuzzo) [reply kafka-java-auth/src/main/java/com/google/cloud/hosted/kafka/auth/GcpLoginCallbackHandler.java:21]: Thanks, added

File: kafka-java-auth/src/main/java/com/google/cloud/hosted/kafka/auth/GcpLoginCallbackHandler.java (hunk 1 above)
Comment (acocuzzo) [reply kafka-java-auth/src/main/java/com/google/cloud/hosted/kafka/auth/GcpLoginCallbackHandler.java:115]: Thanks, added

Comment (acocuzzo) [reply kafka-java-auth/src/main/java/com/google/cloud/hosted/kafka/auth/GcpLoginCallbackHandler.java:115]: Actually, reverted as I think we want to be compatible with Maven 8

**Review by davidtorres — APPROVED** [review]
